CC := gcc
SRCD := src
TSTD := tests
BLDD := build
BIND := bin
INCD := include
LIBD := lib
UTILD := util

MAIN  := $(BLDD)/main.o
AUX  := $(BLDD)/client.o
LIB := $(LIBD)/xacto.a

ALL_SRCF := $(shell find $(SRCD) -type f -name *.c)
ALL_LIBF := $(shell find $(LIBD) -type f -name *.o)
ALL_OBJF := $(patsubst $(SRCD)/%,$(BLDD)/%,$(ALL_SRCF:.c=.o))
ALL_FUNCF := $(filter-out $(MAIN) $(AUX), $(ALL_OBJF))

TEST_SRC := $(shell find $(TSTD) -type f -name *.c)

INC := -I $(INCD)

CFLAGS := -Wall -Werror -Wno-unused-function -MMD
COLORF := -DCOLOR
DFLAGS := -g -DDEBUG -DCOLOR
PRINT_STAMENTS := -DERROR -DSUCCESS -DWARN -DINFO

STD := -std=gnu11
TEST_LIB := -lcriterion
LIBS := -lpthread
EXCLUDES := excludes.h

CFLAGS += $(STD)

EXEC := xacto
TEST_EXEC := $(EXEC)_tests
AUX_EXEC := client

.PHONY: clean all setup debug

all: setup $(BIND)/$(EXEC) $(BIND)/$(TEST_EXEC) $(UTILD)/$(AUX_EXEC)

debug: CFLAGS += $(DFLAGS) $(PRINT_STAMENTS) $(COLORF)
debug: all

setup: $(BIND) $(BLDD) $(LIBD) $(UTILD)
$(BIND):
	mkdir -p $(BIND)
$(BLDD):
	mkdir -p $(BLDD)
$(LIBD):
	mkdir -p $(LIBD)
$(UTILD):
	mkdir -p $(UTILD)

$(BIND)/$(EXEC): $(MAIN) $(ALL_FUNCF) $(ALL_LIBF)
	$(CC) $^ -o $@ $(LIBS)

$(BIND)/$(TEST_EXEC): $(ALL_FUNCF) $(TEST_SRC) $(ALL_LIBF)
	$(CC) $(CFLAGS) $(INC) $(ALL_FUNCF) $(TEST_SRC) $(ALL_LIBF) $(TEST_LIB) $(LIBS) -o $@

$(UTILD)/$(AUX_EXEC): $(AUX) $(ALL_FUNCF) $(LIB)
	$(CC) $(CFLAGS) $(INC) $(AUX) $(ALL_FUNCF) $(LIB) -o $(UTILD)/$(AUX_EXEC) $(LIBS)

$(BLDD)/%.o: $(SRCD)/%.c
	$(CC) $(CFLAGS) $(INC) -c -o $@ $<

$(LIBD)/%.a: $(ALL_FUNCF)
	$(AR) r $@ $^

clean:
	rm -rf $(BLDD) $(BIND)

$(INCD)/$(EXCLUDES): $(BIND)/$(EXEC)
	rm -f $@
	touch $@
	if nm $(BIND)/$(EXEC) | grep INSTRUCTOR_CLIENT_REGISTRY > /dev/null; then \
           echo "#define NO_CLIENT_REGISTRY" >> $@; \
        fi
	if nm $(BIND)/$(EXEC) | grep INSTRUCTOR_DATA > /dev/null; then \
           echo "#define NO_DATA" >> $@; \
        fi
	if nm $(BIND)/$(EXEC) | grep INSTRUCTOR_PROTOCOL > /dev/null; then \
           echo "#define NO_PROTOCOL" >> $@; \
        fi
	if nm $(BIND)/$(EXEC) | grep INSTRUCTOR_SERVER > /dev/null; then \
           echo "#define NO_SERVER" >> $@; \
        fi
	if nm $(BIND)/$(EXEC) | grep INSTRUCTOR_STORE > /dev/null; then \
           echo "#define NO_STORE" >> $@; \
        fi
	if nm $(BIND)/$(EXEC) | grep INSTRUCTOR_TRANSACTION > /dev/null; then \
           echo "#define NO_TRANSACTION" >> $@; \
        fi

.PRECIOUS: $(BLDD)/*.d
-include $(BLDD)/*.d
